In [26]:
# Import the dependencies
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [27]:
# Import weather database as a new dataframe
weather_py_df = pd.read_csv("weather_data/WeatherPy_database.csv")
weather_py_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,Hilo,US,19.73,-155.09,77.00,78,90,5.82,light rain,0.00,0
1,1,Borujerd,IR,33.90,48.75,66.25,31,0,6.02,clear sky,0.00,0
2,2,Omboue,GA,-1.57,9.26,72.19,87,97,7.78,overcast clouds,0.00,0
3,3,Tsihombe,GA,-1.57,9.26,72.19,87,97,7.78,overcast clouds,0.00,0
4,4,Cuddapah,IN,14.47,78.82,77.56,83,100,7.36,light rain,0.14,0

In [28]:
# Configure gmaps to use your Google API key
gmaps.configure(api_key=g_key)

In [29]:
# Get the maximum temperature
max_temp = weather_py_df["Max Temp"]
temps = []
[max(temp, 0) for temp in max_temp]
    
# Get the latitude and longitude.
locations = weather_py_df[["Lat", "Lng"]]

# Get the maximum temperature
max_temp = weather_py_df["Max Temp"]

In [30]:
# Ask the customer to add a minimum and maximum temperature value
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
yes_rain = str(input("Do you want it to be raining?(yes/no)"))
yes_snow = str(input("Do you want it to be snowing?(yes/no)"))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 100
Do you want it to be raining?(yes/no)no
Do you want it to be snowing?(yes/no)no

In [31]:
# Filter the dataset to find the cities that fit the criteria    
preferred_cities_temp_df = weather_py_df.loc[(weather_py_df["Max Temp"] <= max_temp) & \
                                       (weather_py_df["Max Temp"] >= min_temp)]

preferred_cities_temp_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,Hilo,US,19.73,-155.09,77.00,78,90,5.82,light rain,0.00,0
1,1,Borujerd,IR,33.90,48.75,66.25,31,0,6.02,clear sky,0.00,0
2,2,Omboue,GA,-1.57,9.26,72.19,87,97,7.78,overcast clouds,0.00,0
3,3,Tsihombe,GA,-1.57,9.26,72.19,87,97,7.78,overcast clouds,0.00,0
4,4,Cuddapah,IN,14.47,78.82,77.56,83,100,7.36,light rain,0.14,0
5,5,Orbetello,IT,42.44,11.22,73.40,73,20,8.05,few clouds,0.00,0
6,6,Yellowknife,CA,62.46,-114.35,60.80,72,75,12.75,broken clouds,0.00,0
7,7,Lethem,GY,3.38,-59.80,86.41,63,57,3.24,light rain,0.43,0
11,11,La Rioja,ES,42.25,-2.50,71.60,43,0,5.82,clear sky,0.00,0
13,13,Shihezi,CN,44.30,86.03,73.31,33,25,2.24,scattered clouds,0.00,0

In [32]:
# Editing DataFrame for rain preference
if yes_rain == "no":
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Rain(inches)"] == 0]
else:
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Rain(inches)"] > 0]
preferred_cities_temp_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,Hilo,US,19.73,-155.09,77.00,78,90,5.82,light rain,0.0,0
1,1,Borujerd,IR,33.90,48.75,66.25,31,0,6.02,clear sky,0.0,0
2,2,Omboue,GA,-1.57,9.26,72.19,87,97,7.78,overcast clouds,0.0,0
3,3,Tsihombe,GA,-1.57,9.26,72.19,87,97,7.78,overcast clouds,0.0,0
5,5,Orbetello,IT,42.44,11.22,73.40,73,20,8.05,few clouds,0.0,0
6,6,Yellowknife,CA,62.46,-114.35,60.80,72,75,12.75,broken clouds,0.0,0
11,11,La Rioja,ES,42.25,-2.50,71.60,43,0,5.82,clear sky,0.0,0
13,13,Shihezi,CN,44.30,86.03,73.31,33,25,2.24,scattered clouds,0.0,0
14,14,Havoysund,NO,71.00,24.66,60.80,93,75,3.36,broken clouds,0.0,0
19,19,Skibbereen,IE,51.55,-9.27,60.80,82,75,20.80,broken clouds,0.0,0

In [33]:
# Editing DataFrame for snow preference
if yes_snow == "no":
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Snow(inches)"] == 0]
else:
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Snow(inches)"] > 0]
preferred_cities_temp_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,Hilo,US,19.73,-155.09,77.00,78,90,5.82,light rain,0.0,0
1,1,Borujerd,IR,33.90,48.75,66.25,31,0,6.02,clear sky,0.0,0
2,2,Omboue,GA,-1.57,9.26,72.19,87,97,7.78,overcast clouds,0.0,0
3,3,Tsihombe,GA,-1.57,9.26,72.19,87,97,7.78,overcast clouds,0.0,0
5,5,Orbetello,IT,42.44,11.22,73.40,73,20,8.05,few clouds,0.0,0
6,6,Yellowknife,CA,62.46,-114.35,60.80,72,75,12.75,broken clouds,0.0,0
11,11,La Rioja,ES,42.25,-2.50,71.60,43,0,5.82,clear sky,0.0,0
13,13,Shihezi,CN,44.30,86.03,73.31,33,25,2.24,scattered clouds,0.0,0
14,14,Havoysund,NO,71.00,24.66,60.80,93,75,3.36,broken clouds,0.0,0
19,19,Skibbereen,IE,51.55,-9.27,60.80,82,75,20.80,broken clouds,0.0,0

In [34]:
# Adding the cities to a marker layer map with a pop-up marker for each city that includes
hotel_df = preferred_cities_temp_df[["City", "Country", "Max Temp", "Current Description","Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Hilo,US,77.00,light rain,19.73,-155.09,
1,Borujerd,IR,66.25,clear sky,33.90,48.75,
2,Omboue,GA,72.19,overcast clouds,-1.57,9.26,
3,Tsihombe,GA,72.19,overcast clouds,-1.57,9.26,
5,Orbetello,IT,73.40,few clouds,42.44,11.22,
6,Yellowknife,CA,60.80,broken clouds,62.46,-114.35,
11,La Rioja,ES,71.60,clear sky,42.25,-2.50,
13,Shihezi,CN,73.31,scattered clouds,44.30,86.03,
14,Havoysund,NO,60.80,broken clouds,71.00,24.66,
19,Skibbereen,IE,60.80,broken clouds,51.55,-9.27,

In [35]:
# Set the parameters to search for a hotel 
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}

# Use base URL to search for hotels in Paris
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# Make request and get the JSON data from the search
hotels = requests.get(base_url, params=params).json()

In [36]:
# Iterate through the DataFrame
for index, row in hotel_df.iterrows():
    
    # Get the latitude and longitude
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search
    hotels = requests.get(base_url, params=params).json()
   
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
    
# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
-----------------------------
Data Retrieval Complete
-----------------------------

In [37]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Hilo,US,77.00,light rain,19.73,-155.09,Hilo Hawaiian Hotel
1,Borujerd,IR,66.25,clear sky,33.90,48.75,Zagros International Hotel
2,Omboue,GA,72.19,overcast clouds,-1.57,9.26,Hotel Olako
3,Tsihombe,GA,72.19,overcast clouds,-1.57,9.26,Hotel Olako
5,Orbetello,IT,73.40,few clouds,42.44,11.22,Argentario Golf Resort & Spa
6,Yellowknife,CA,60.80,broken clouds,62.46,-114.35,The Explorer Hotel
11,La Rioja,ES,71.60,clear sky,42.25,-2.50,Casa Concejos
13,Shihezi,CN,73.31,scattered clouds,44.30,86.03,Home Inn Shihezi Dongwu Road Century Square
14,Havoysund,NO,60.80,broken clouds,71.00,24.66,Arctic View Glamping & Restaurant
19,Skibbereen,IE,60.80,broken clouds,51.55,-9.27,The West Cork Hotel

In [38]:
# Create the output file (CSV)
output_data_file = "weather_data/WeatherPy_vacation.csv"

# Export the City_Data into a CSV
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [39]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [40]:
# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [41]:
# Add the vacation spots and marker for each city
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=5.0)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))