In [1]:
# Import the dependencies
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [2]:
# Import weather database as a new dataframe
weather_py_df = pd.read_csv("weather_data/WeatherPy_database.csv")
weather_py_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,San Andres,CO,12.58,-81.70,78.80,88,75,14.99,light intensity drizzle,0.0,0
1,1,Cape Town,ZA,-33.93,18.42,66.00,45,0,16.11,clear sky,0.0,0
2,2,Kruisfontein,ZA,-34.00,24.73,65.34,27,0,9.73,clear sky,0.0,0
3,3,Vestmannaeyjar,IS,63.44,-20.27,51.80,87,90,8.05,drizzle,0.0,0
4,4,Ushuaia,AR,-54.80,-68.30,35.60,80,75,18.34,shower rain,0.0,0

In [3]:
# Configure gmaps to use your Google API key
gmaps.configure(api_key=g_key)

In [4]:
# Get the maximum temperature
max_temp = weather_py_df["Max Temp"]
temps = []
[max(temp, 0) for temp in max_temp]
    
# Get the latitude and longitude.
locations = weather_py_df[["Lat", "Lng"]]

# Get the maximum temperature
max_temp = weather_py_df["Max Temp"]

In [5]:
# Ask the customer to add a minimum and maximum temperature value
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
yes_rain = str(input("Do you want it to be raining?(yes/no)"))
yes_snow = str(input("Do you want it to be snowing?(yes/no)"))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining?(yes/no)no
Do you want it to be snowing?(yes/no)no

In [6]:
# Filter the dataset to find the cities that fit the criteria    
preferred_cities_temp_df = weather_py_df.loc[(weather_py_df["Max Temp"] <= max_temp) & \
                                       (weather_py_df["Max Temp"] >= min_temp)]

preferred_cities_temp_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,San Andres,CO,12.58,-81.70,78.80,88,75,14.99,light intensity drizzle,0.0,0
7,7,Kulhudhuffushi,MV,6.62,73.07,84.22,66,100,2.89,overcast clouds,0.0,0
10,10,Danville,US,36.59,-79.39,77.00,73,1,4.70,clear sky,0.0,0
11,11,Opobo,US,36.59,-79.39,77.00,73,1,4.70,clear sky,0.0,0
17,17,Rikitea,PF,-23.12,-134.97,70.77,72,0,18.32,clear sky,0.0,0
24,24,San Cristobal,VE,7.77,-72.22,78.80,74,40,2.24,scattered clouds,0.0,0
25,25,Yashkino,RU,55.87,85.43,73.40,64,20,4.47,few clouds,0.0,0
27,27,San Patricio,MX,19.22,-104.70,77.00,83,75,6.93,broken clouds,0.0,0
30,30,Banjar,ID,-8.19,114.97,78.80,100,40,10.29,scattered clouds,0.0,0
31,31,Hilo,US,19.73,-155.09,75.20,73,90,3.36,overcast clouds,0.0,0

In [7]:
# Editing DataFrame for rain preference
if yes_rain == "no":
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Rain(inches)"] == 0]
else:
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Rain(inches)"] > 0]
preferred_cities_temp_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,San Andres,CO,12.58,-81.70,78.80,88,75,14.99,light intensity drizzle,0.0,0
7,7,Kulhudhuffushi,MV,6.62,73.07,84.22,66,100,2.89,overcast clouds,0.0,0
10,10,Danville,US,36.59,-79.39,77.00,73,1,4.70,clear sky,0.0,0
11,11,Opobo,US,36.59,-79.39,77.00,73,1,4.70,clear sky,0.0,0
17,17,Rikitea,PF,-23.12,-134.97,70.77,72,0,18.32,clear sky,0.0,0
24,24,San Cristobal,VE,7.77,-72.22,78.80,74,40,2.24,scattered clouds,0.0,0
25,25,Yashkino,RU,55.87,85.43,73.40,64,20,4.47,few clouds,0.0,0
27,27,San Patricio,MX,19.22,-104.70,77.00,83,75,6.93,broken clouds,0.0,0
30,30,Banjar,ID,-8.19,114.97,78.80,100,40,10.29,scattered clouds,0.0,0
31,31,Hilo,US,19.73,-155.09,75.20,73,90,3.36,overcast clouds,0.0,0

In [8]:
# Editing DataFrame for snow preference
if yes_snow == "no":
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Snow(inches)"] == 0]
else:
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Snow(inches)"] > 0]
preferred_cities_temp_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,San Andres,CO,12.58,-81.70,78.80,88,75,14.99,light intensity drizzle,0.0,0
7,7,Kulhudhuffushi,MV,6.62,73.07,84.22,66,100,2.89,overcast clouds,0.0,0
10,10,Danville,US,36.59,-79.39,77.00,73,1,4.70,clear sky,0.0,0
11,11,Opobo,US,36.59,-79.39,77.00,73,1,4.70,clear sky,0.0,0
17,17,Rikitea,PF,-23.12,-134.97,70.77,72,0,18.32,clear sky,0.0,0
24,24,San Cristobal,VE,7.77,-72.22,78.80,74,40,2.24,scattered clouds,0.0,0
25,25,Yashkino,RU,55.87,85.43,73.40,64,20,4.47,few clouds,0.0,0
27,27,San Patricio,MX,19.22,-104.70,77.00,83,75,6.93,broken clouds,0.0,0
30,30,Banjar,ID,-8.19,114.97,78.80,100,40,10.29,scattered clouds,0.0,0
31,31,Hilo,US,19.73,-155.09,75.20,73,90,3.36,overcast clouds,0.0,0

In [9]:
# Adding the cities to a marker layer map with a pop-up marker for each city that includes
hotel_df = preferred_cities_temp_df[["City", "Country", "Max Temp", "Current Description","Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,San Andres,CO,78.80,light intensity drizzle,12.58,-81.70,
7,Kulhudhuffushi,MV,84.22,overcast clouds,6.62,73.07,
10,Danville,US,77.00,clear sky,36.59,-79.39,
11,Opobo,US,77.00,clear sky,36.59,-79.39,
17,Rikitea,PF,70.77,clear sky,-23.12,-134.97,
24,San Cristobal,VE,78.80,scattered clouds,7.77,-72.22,
25,Yashkino,RU,73.40,few clouds,55.87,85.43,
27,San Patricio,MX,77.00,broken clouds,19.22,-104.70,
30,Banjar,ID,78.80,scattered clouds,-8.19,114.97,
31,Hilo,US,75.20,overcast clouds,19.73,-155.09,

In [10]:
# Set the parameters to search for a hotel in Paris
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}

# Use base URL to search for hotels in Paris
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# Make request and get the JSON data from the search
hotels = requests.get(base_url, params=params).json()

In [11]:
# Iterate through the DataFrame
for index, row in hotel_df.iterrows():
    
    # Get the latitude and longitude
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search
    hotels = requests.get(base_url, params=params).json()
   
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
    
# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
-----------------------------
Data Retrieval Complete
-----------------------------

In [12]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,San Andres,CO,78.80,light intensity drizzle,12.58,-81.70,Hotel Arena Blanca
7,Kulhudhuffushi,MV,84.22,overcast clouds,6.62,73.07,Haajy Guest House 1
10,Danville,US,77.00,clear sky,36.59,-79.39,Holiday Inn Express Danville
11,Opobo,US,77.00,clear sky,36.59,-79.39,Holiday Inn Express Danville
17,Rikitea,PF,70.77,clear sky,-23.12,-134.97,Pension Maro'i
24,San Cristobal,VE,78.80,scattered clouds,7.77,-72.22,Pirineos
25,Yashkino,RU,73.40,few clouds,55.87,85.43,"Gostinitsa ""Berozka"""
27,San Patricio,MX,77.00,broken clouds,19.22,-104.70,Hotel Cabo Blanco
30,Banjar,ID,78.80,scattered clouds,-8.19,114.97,The Hamsa Resort
31,Hilo,US,75.20,overcast clouds,19.73,-155.09,Hilo Hawaiian Hotel

In [13]:
# Create the output file (CSV)
output_data_file = "weather_data/WeatherPy_vacation.csv"

# Export the City_Data into a CSV
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [14]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [15]:
# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [16]:
#import matplotlib.pyplot as plt

In [17]:
# Add the vacation spots and marker for each city
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=5.0)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))