In [18]:
# Import the dependencies
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [19]:
# Import weather database as a new dataframe
weather_py_df = pd.read_csv("weather_data/WeatherPy_database.csv")
weather_py_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,Busselton,AU,-33.65,115.33,55.99,81,44,13.24,scattered clouds,0.0,0
1,1,Punta Arenas,CL,-53.15,-70.92,37.40,78,20,21.92,few clouds,0.0,0
2,2,Esperance,AU,-33.87,121.90,48.20,66,48,18.34,scattered clouds,0.0,0
3,3,Bluff,NZ,-46.60,168.33,39.00,83,56,3.00,broken clouds,0.0,0
4,4,Mar Del Plata,AR,-38.00,-57.56,50.00,37,20,17.22,few clouds,0.0,0

In [20]:
# Configure gmaps to use your Google API key
gmaps.configure(api_key=g_key)

In [21]:
# Get the maximum temperature
max_temp = weather_py_df["Max Temp"]
temps = []
[max(temp, 0) for temp in max_temp]
    
# Get the latitude and longitude.
locations = weather_py_df[["Lat", "Lng"]]

# Get the maximum temperature
max_temp = weather_py_df["Max Temp"]

In [22]:
# Ask the customer to add a minimum and maximum temperature value
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
yes_rain = str(input("Do you want it to be raining?(yes/no)"))
yes_snow = str(input("Do you want it to be snowing?(yes/no)"))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 100
Do you want it to be raining?(yes/no)no
Do you want it to be snowing?(yes/no)no

In [23]:
# Filter the dataset to find the cities that fit the criteria    
preferred_cities_temp_df = weather_py_df.loc[(weather_py_df["Max Temp"] <= max_temp) & \
                                       (weather_py_df["Max Temp"] >= min_temp)]

preferred_cities_temp_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
5,5,Tiarei,PF,-17.53,-149.33,77.00,69,75,1.12,broken clouds,0.0,0
6,6,Sept-Iles,CA,50.20,-66.38,69.80,88,90,9.17,overcast clouds,0.0,0
9,9,Ponta Do Sol,PT,32.67,-17.10,73.99,70,0,3.74,clear sky,0.0,0
10,10,Wlodawa,PL,51.55,23.55,63.00,55,1,5.46,clear sky,0.0,0
15,15,Ampanihy,MG,-24.70,44.75,65.70,80,5,7.27,clear sky,0.0,0
17,17,Cape Town,ZA,-33.93,18.42,60.01,47,0,20.80,clear sky,0.0,0
18,18,Saint George,US,37.10,-113.58,100.00,18,1,3.11,clear sky,0.0,0
19,19,Chapais,CA,49.78,-74.85,64.40,88,90,11.41,overcast clouds,0.0,0
20,20,Saint-Pierre,RE,-21.34,55.48,69.80,73,20,8.05,few clouds,0.0,0
22,22,Georgetown,MY,5.41,100.34,82.40,88,20,4.70,few clouds,0.0,0

In [24]:
# Editing DataFrame for rain preference
if yes_rain == "no":
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Rain(inches)"] == 0]
else:
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Rain(inches)"] > 0]
preferred_cities_temp_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
5,5,Tiarei,PF,-17.53,-149.33,77.00,69,75,1.12,broken clouds,0.0,0
6,6,Sept-Iles,CA,50.20,-66.38,69.80,88,90,9.17,overcast clouds,0.0,0
9,9,Ponta Do Sol,PT,32.67,-17.10,73.99,70,0,3.74,clear sky,0.0,0
10,10,Wlodawa,PL,51.55,23.55,63.00,55,1,5.46,clear sky,0.0,0
15,15,Ampanihy,MG,-24.70,44.75,65.70,80,5,7.27,clear sky,0.0,0
17,17,Cape Town,ZA,-33.93,18.42,60.01,47,0,20.80,clear sky,0.0,0
18,18,Saint George,US,37.10,-113.58,100.00,18,1,3.11,clear sky,0.0,0
19,19,Chapais,CA,49.78,-74.85,64.40,88,90,11.41,overcast clouds,0.0,0
20,20,Saint-Pierre,RE,-21.34,55.48,69.80,73,20,8.05,few clouds,0.0,0
22,22,Georgetown,MY,5.41,100.34,82.40,88,20,4.70,few clouds,0.0,0

In [25]:
# Editing DataFrame for snow preference
if yes_snow == "no":
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Snow(inches)"] == 0]
else:
    preferred_cities_temp_df = preferred_cities_temp_df.loc[preferred_cities_temp_df["Snow(inches)"] > 0]
preferred_cities_temp_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
5,5,Tiarei,PF,-17.53,-149.33,77.00,69,75,1.12,broken clouds,0.0,0
6,6,Sept-Iles,CA,50.20,-66.38,69.80,88,90,9.17,overcast clouds,0.0,0
9,9,Ponta Do Sol,PT,32.67,-17.10,73.99,70,0,3.74,clear sky,0.0,0
10,10,Wlodawa,PL,51.55,23.55,63.00,55,1,5.46,clear sky,0.0,0
15,15,Ampanihy,MG,-24.70,44.75,65.70,80,5,7.27,clear sky,0.0,0
17,17,Cape Town,ZA,-33.93,18.42,60.01,47,0,20.80,clear sky,0.0,0
18,18,Saint George,US,37.10,-113.58,100.00,18,1,3.11,clear sky,0.0,0
19,19,Chapais,CA,49.78,-74.85,64.40,88,90,11.41,overcast clouds,0.0,0
20,20,Saint-Pierre,RE,-21.34,55.48,69.80,73,20,8.05,few clouds,0.0,0
22,22,Georgetown,MY,5.41,100.34,82.40,88,20,4.70,few clouds,0.0,0

In [26]:
# Adding the cities to a marker layer map with a pop-up marker for each city that includes
hotel_df = preferred_cities_temp_df[["City", "Country", "Max Temp", "Current Description","Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Tiarei,PF,77.00,broken clouds,-17.53,-149.33,
6,Sept-Iles,CA,69.80,overcast clouds,50.20,-66.38,
9,Ponta Do Sol,PT,73.99,clear sky,32.67,-17.10,
10,Wlodawa,PL,63.00,clear sky,51.55,23.55,
15,Ampanihy,MG,65.70,clear sky,-24.70,44.75,
17,Cape Town,ZA,60.01,clear sky,-33.93,18.42,
18,Saint George,US,100.00,clear sky,37.10,-113.58,
19,Chapais,CA,64.40,overcast clouds,49.78,-74.85,
20,Saint-Pierre,RE,69.80,few clouds,-21.34,55.48,
22,Georgetown,MY,82.40,few clouds,5.41,100.34,

In [27]:
# Iterate through the DataFrame
for index, row in hotel_df.iterrows():
    
    # Get the latitude and longitude
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search
    hotels = requests.get(base_url, params=params).json()
   
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
    
# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
-----------------------------
Data Retrieval Complete
-----------------------------

In [28]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Tiarei,PF,77.00,broken clouds,-17.53,-149.33,Le Rocher de Tahiti
6,Sept-Iles,CA,69.80,overcast clouds,50.20,-66.38,Comfort Inn
9,Ponta Do Sol,PT,73.99,clear sky,32.67,-17.10,Hotel do Campo
10,Wlodawa,PL,63.00,clear sky,51.55,23.55,Ośrodek Wypoczynkowy Ranczo
15,Ampanihy,MG,65.70,clear sky,-24.70,44.75,Angora Hotel
17,Cape Town,ZA,60.01,clear sky,-33.93,18.42,Southern Sun Waterfront Cape Town
18,Saint George,US,100.00,clear sky,37.10,-113.58,Best Western Plus Abbey Inn
19,Chapais,CA,64.40,overcast clouds,49.78,-74.85,Hôtel Opémiska
20,Saint-Pierre,RE,69.80,few clouds,-21.34,55.48,Lindsey Hôtel
22,Georgetown,MY,82.40,few clouds,5.41,100.34,Cititel Penang

In [29]:
# Create the output file (CSV)
output_data_file = "weather_data/WeatherPy_vacation.csv"

# Export the City_Data into a CSV
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [30]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [31]:
# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [32]:
# Add the vacation spots and marker for each city
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=5.0)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))